
var WasmEncoder = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(WasmEncoder) {
  WasmEncoder = WasmEncoder || {};

var c;c||(c=typeof WasmEncoder !== 'undefined' ? WasmEncoder : {});var f={},m;for(m in c)c.hasOwnProperty(m)&&(f[m]=c[m]);c.arguments=[];c.thisProgram="./this.program";c.quit=function(a,b){throw b;};c.preRun=[];c.postRun=[];var n=!1,p=!1,t=!1,aa=!1;n="object"===typeof window;p="function"===typeof importScripts;t="object"===typeof process&&"function"===typeof require&&!n&&!p;aa=!n&&!t&&!p;var u="";function ba(a){return c.locateFile?c.locateFile(a,u):u+a}
if(t){u=__dirname+"/";var ca,da;c.read=function(a,b){ca||(ca=require("fs"));da||(da=require("path"));a=da.normalize(a);a=ca.readFileSync(a);return b?a:a.toString()};c.readBinary=function(a){a=c.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(c.thisProgram=process.argv[1].replace(/\\/g,"/"));c.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof v))throw a;});process.on("unhandledRejection",w);c.quit=function(a){process.exit(a)};
c.inspect=function(){return"[Emscripten Module object]"}}else if(aa)"undefined"!=typeof read&&(c.read=function(a){return read(a)}),c.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?c.arguments=scriptArgs:"undefined"!=typeof arguments&&(c.arguments=arguments),"function"===typeof quit&&(c.quit=function(a){quit(a)});else if(n||p)p?u=self.location.href:document.currentScript&&
(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="",c.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(c.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),c.readAsync=function(a,b,d){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||
0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)},c.setWindowTitle=function(a){document.title=a};var ea=c.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),x=c.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ea);for(m in f)f.hasOwnProperty(m)&&(c[m]=f[m]);f=void 0;function y(a){var b=z;z=z+a+15&-16;return b}
function fa(a){var b=A[C>>2];a=b+a+15&-16;A[C>>2]=a;return a>=D&&!ha()?(A[C>>2]=b,0):b}function ia(a){var b;b||(b=16);return Math.ceil(a/b)*b}var ja={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},ka=!1;function assert(a,b){a||w("Assertion failed: "+b)}
function la(a,b){if("number"===typeof a){var d=!0;var e=a}else d=!1,e=a.length;b=4==b?g:["function"===typeof E?E:y,ma,y,fa][void 0===b?2:b](Math.max(e,1));if(d){var g=b;assert(0==(b&3));for(a=b+(e&-4);g<a;g+=4)A[g>>2]=0;for(a=b+e;g<a;)F[g++>>0]=0;return b}a.subarray||a.slice?G.set(a,b):G.set(new Uint8Array(a),b);return b}
function H(a){var b;if(0===b||!a)return"";for(var d=0,e,g=0;;){e=G[a+g>>0];d|=e;if(0==e&&!b)break;g++;if(b&&g==b)break}b||(b=g);e="";if(128>d){for(;0<b;)d=String.fromCharCode.apply(String,G.subarray(a,a+Math.min(b,1024))),e=e?e+d:d,a+=1024,b-=1024;return e}return na(G,a)}var oa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function na(a,b){for(var d=b;a[d];)++d;if(16<d-b&&a.subarray&&oa)return oa.decode(a.subarray(b,d));for(d="";;){var e=a[b++];if(!e)return d;if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=a[b++]&63;if(224==(e&240))e=(e&15)<<12|g<<6|k;else{var h=a[b++]&63;if(240==(e&248))e=(e&7)<<18|g<<12|k<<6|h;else{var l=a[b++]&63;if(248==(e&252))e=(e&3)<<24|g<<18|k<<12|h<<6|l;else{var B=a[b++]&63;e=(e&1)<<30|g<<24|k<<18|h<<12|l<<6|B}}}65536>e?d+=String.fromCharCode(e):(e-=
65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}}
function pa(a,b,d,e){if(!(0<e))return 0;var g=d;e=d+e-1;for(var k=0;k<a.length;++k){var h=a.charCodeAt(k);if(55296<=h&&57343>=h){var l=a.charCodeAt(++k);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(d>=e)break;b[d++]=h}else{if(2047>=h){if(d+1>=e)break;b[d++]=192|h>>6}else{if(65535>=h){if(d+2>=e)break;b[d++]=224|h>>12}else{if(2097151>=h){if(d+3>=e)break;b[d++]=240|h>>18}else{if(67108863>=h){if(d+4>=e)break;b[d++]=248|h>>24}else{if(d+5>=e)break;b[d++]=252|h>>30;b[d++]=128|h>>24&63}b[d++]=128|h>>18&63}b[d++]=
128|h>>12&63}b[d++]=128|h>>6&63}b[d++]=128|h&63}}b[d]=0;return d-g}function qa(a){for(var b=0,d=0;d<a.length;++d){var e=a.charCodeAt(d);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++d)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:2097151>=e?b+4:67108863>=e?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var ra=65536,sa=16777216,ta=16777216;function ua(a,b){0<a%b&&(a+=b-a%b);return a}var buffer,F,G,A;
function wa(){c.HEAP8=F=new Int8Array(buffer);c.HEAP16=new Int16Array(buffer);c.HEAP32=A=new Int32Array(buffer);c.HEAPU8=G=new Uint8Array(buffer);c.HEAPU16=new Uint16Array(buffer);c.HEAPU32=new Uint32Array(buffer);c.HEAPF32=new Float32Array(buffer);c.HEAPF64=new Float64Array(buffer)}var J,z,K,xa,L,ya,za,C;J=z=xa=L=ya=za=C=0;K=!1;c.reallocBuffer||(c.reallocBuffer=function(a){try{var b=F;var d=new ArrayBuffer(a);(new Int8Array(d)).set(b)}catch(e){return!1}return Aa(d)?d:!1});
function ha(){var a=c.usingWasm?ra:sa,b=2147483648-a;if(A[C>>2]>b)return!1;var d=D;for(D=Math.max(D,ta);D<A[C>>2];)536870912>=D?D=ua(2*D,a):D=Math.min(ua((3*D+2147483648)/4,a),b);a=c.reallocBuffer(D);if(!a||a.byteLength!=D)return D=d,!1;c.buffer=buffer=a;wa();return!0}var Ba;try{Ba=Function.prototype.call.bind(Object.getOwnPropertyDescriptor(ArrayBuffer.prototype,"byteLength").get),Ba(new ArrayBuffer(4))}catch(a){Ba=function(b){return b.byteLength}}
var Ca=c.TOTAL_STACK||5242880,D=c.TOTAL_MEMORY||16777216;D<Ca&&x("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+D+"! (TOTAL_STACK="+Ca+")");c.buffer?buffer=c.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(c.wasmMemory=new WebAssembly.Memory({initial:D/ra}),buffer=c.wasmMemory.buffer):buffer=new ArrayBuffer(D),c.buffer=buffer);wa();
function M(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var d=b.ua;"number"===typeof d?void 0===b.pa?c.dynCall_v(d):c.dynCall_vi(d,b.pa):d(void 0===b.pa?null:b.pa)}}}var Da=[],Ea=[],Fa=[],Ga=[],Ha=[],N=!1;function Ia(){var a=c.preRun.shift();Da.unshift(a)}var Ja=Math.abs,La=Math.trunc,O=0,Ma=null,P=null;c.preloadedImages={};c.preloadedAudios={};
function Q(a){return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}
(function(){function a(){try{if(c.wasmBinary)return new Uint8Array(c.wasmBinary);if(c.readBinary)return c.readBinary(g);throw"both async and sync fetching of the wasm failed";}catch(q){w(q)}}function b(){return c.wasmBinary||!n&&!p||"function"!==typeof fetch?new Promise(function(b){b(a())}):fetch(g,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+g+"'";return a.arrayBuffer()}).catch(function(){return a()})}function d(a){function d(a){l=a.exports;if(l.memory){a=
l.memory;var b=c.buffer;a.byteLength<b.byteLength&&x("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");b=new Int8Array(b);(new Int8Array(a)).set(b);c.buffer=buffer=a;wa()}c.asm=l;c.usingWasm=!0;O--;c.monitorRunDependencies&&c.monitorRunDependencies(O);0==O&&(null!==Ma&&(clearInterval(Ma),Ma=null),P&&(a=P,P=null,a()))}function e(a){d(a.instance)}function va(a){b().then(function(a){return WebAssembly.instantiate(a,h)}).then(a,function(a){x("failed to asynchronously prepare wasm: "+
a);w(a)})}if("object"!==typeof WebAssembly)return x("no native wasm support detected"),!1;if(!(c.wasmMemory instanceof WebAssembly.Memory))return x("no native wasm Memory in use"),!1;a.memory=c.wasmMemory;h.global={NaN:NaN,Infinity:Infinity};h["global.Math"]=Math;h.env=a;O++;c.monitorRunDependencies&&c.monitorRunDependencies(O);if(c.instantiateWasm)try{return c.instantiateWasm(h,d)}catch(ab){return x("Module.instantiateWasm callback failed with error: "+ab),!1}c.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||
Q(g)||"function"!==typeof fetch?va(e):WebAssembly.instantiateStreaming(fetch(g,{credentials:"same-origin"}),h).then(e,function(a){x("wasm streaming compile failed: "+a);x("falling back to ArrayBuffer instantiation");va(e)});return{}}var e="WasmEncoder.wast",g="WasmEncoder.wasm",k="WasmEncoder.temp.asm.js";Q(e)||(e=ba(e));Q(g)||(g=ba(g));Q(k)||(k=ba(k));var h={global:null,env:null,asm2wasm:ja,parent:c},l=null;c.asmPreload=c.asm;var B=c.reallocBuffer;c.reallocBuffer=function(a){if("asmjs"===r)var b=
B(a);else a:{a=ua(a,c.usingWasm?ra:sa);var d=c.buffer.byteLength;if(c.usingWasm)try{b=-1!==c.wasmMemory.grow((a-d)/65536)?c.buffer=c.wasmMemory.buffer:null;break a}catch(va){b=null;break a}b=void 0}return b};var r="";c.asm=function(a,b){if(!b.table){a=c.wasmTableSize;void 0===a&&(a=1024);var e=c.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==e?new WebAssembly.Table({initial:a,maximum:e,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):
Array(a);c.wasmTable=b.table}b.__memory_base||(b.__memory_base=c.STATIC_BASE);b.__table_base||(b.__table_base=0);b=d(b);assert(b,"no binaryen method succeeded.");return b}})();J=1024;z=J+1993168;Ea.push({ua:function(){Na()}});c.STATIC_BASE=J;c.STATIC_BUMP=1993168;z+=16;var R={};
function Oa(a){if(Oa.la){var b=A[a>>2];var d=A[b>>2]}else Oa.la=!0,R.USER=R.LOGNAME="web_user",R.PATH="/",R.PWD="/",R.HOME="/home/web_user",R.LANG="C.UTF-8",R._=c.thisProgram,d=K?N?E(1024):fa(1024):y(1024),b=K?N?E(256):fa(256):y(256),A[b>>2]=d,A[a>>2]=b;a=[];var e=0,g;for(g in R)if("string"===typeof R[g]){var k=g+"="+R[g];a.push(k);e+=k.length}if(1024<e)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(g=0;g<a.length;g++){e=k=a[g];for(var h=d,l=0;l<e.length;++l)F[h++>>0]=e.charCodeAt(l);
F[h>>0]=0;A[b+4*g>>2]=d;d+=k.length+1}A[b+4*a.length>>2]=0}var Pa=[null,[],[]],S=0;function T(){S+=4;return A[S-4>>2]}var U={};function Qa(a){c.___errno_location&&(A[c.___errno_location()>>2]=a);return a}function V(){void 0===V.start&&(V.start=Date.now());return 1E3*(Date.now()-V.start)|0}function W(){w()}function X(a){if(0===a)return 0;a=H(a);if(!R.hasOwnProperty(a))return 0;X.la&&Ra(X.la);a=R[a];var b=qa(a)+1,d=E(b);d&&pa(a,F,d,b);X.la=d;return X.la}var Sa=la(Y("GMT"),2);
function Ta(a){return Math.pow(2,a)}function Ua(a){return Math.log(a)/Math.LN10}function Va(a){return Math.log(a)/Math.LN2}
function Wa(){function a(a){return(a=a.toTimeString().match(/\(([A-Za-z ]+)\)$/))?a[1]:"GMT"}if(!Xa){Xa=!0;A[Ya()>>2]=60*(new Date).getTimezoneOffset();var b=new Date(2E3,0,1),d=new Date(2E3,6,1);A[Za()>>2]=Number(b.getTimezoneOffset()!=d.getTimezoneOffset());var e=a(b),g=a(d);e=la(Y(e),0);g=la(Y(g),0);d.getTimezoneOffset()<b.getTimezoneOffset()?(A[Z()>>2]=e,A[Z()+4>>2]=g):(A[Z()>>2]=g,A[Z()+4>>2]=e)}}var Xa;function $a(a){return 0===a%4&&(0!==a%100||0===a%400)}
function bb(a,b){for(var d=0,e=0;e<=b;d+=a[e++]);return d}var cb=[31,29,31,30,31,30,31,31,30,31,30,31],db=[31,28,31,30,31,30,31,31,30,31,30,31];function eb(a,b){for(a=new Date(a.getTime());0<b;){var d=a.getMonth(),e=($a(a.getFullYear())?cb:db)[d];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>d?a.setMonth(d+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
t?W=function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:"undefined"!==typeof dateNow?W=dateNow:"object"===typeof self&&self.performance&&"function"===typeof self.performance.now?W=function(){return self.performance.now()}:"object"===typeof performance&&"function"===typeof performance.now?W=function(){return performance.now()}:W=Date.now;C=y(4);xa=L=ia(z);ya=xa+Ca;za=ia(ya);A[C>>2]=za;K=!0;function Y(a,b){var d=Array(qa(a)+1);a=pa(a,d,0,d.length);b&&(d.length=a);return d}c.wasmTableSize=1194;
c.wasmMaxTableSize=1194;c.ra={};
c.sa={f:w,K:ha,F:function(){return D},A:function(){w("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+D+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")},c:function(a,b,d,e){w("Assertion failed: "+H(a)+", at: "+[b?H(b):"unknown filename",d,e?H(e):"unknown function"])},x:Oa,w:function(){},
q:Qa,v:function(a,b){S=b;try{var d=U.ma();T();var e=T(),g=T(),k=T();FS.Ba(d,e,k);A[g>>2]=d.position;d.va&&0===e&&0===k&&(d.va=null);return 0}catch(h){return"undefined"!==typeof FS&&h instanceof FS.ha||w(h),-h.ia}},Q:function(a,b){S=b;try{var d=U.ma(),e=T(),g=T();return U.Aa(d,e,g)}catch(k){return"undefined"!==typeof FS&&k instanceof FS.ha||w(k),-k.ia}},u:function(a,b){S=b;try{var d=T(),e=T(),g=T();for(b=a=0;b<g;b++){for(var k=A[e+8*b>>2],h=A[e+(8*b+4)>>2],l=0;l<h;l++){var B=d,r=G[k+l],q=Pa[B];assert(q);
0===r||10===r?((1===B?ea:x)(na(q,0)),q.length=0):q.push(r)}a+=h}return a}catch(I){return"undefined"!==typeof FS&&I instanceof FS.ha||w(I),-I.ia}},P:function(a,b){S=b;try{var d=H(T()),e=T();return U.ta(FS.stat,d,e)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.ha||w(g),-g.ia}},O:function(a,b){S=b;try{var d=U.ma(),e=T();return U.ta(FS.stat,d.path,e)}catch(g){return"undefined"!==typeof FS&&g instanceof FS.ha||w(g),-g.ia}},N:function(a,b){S=b;return 0},k:function(a,b){S=b;return 0},M:function(a,
b){S=b;try{var d=U.ma(),e=T(),g=T();return FS.read(d,F,e,g)}catch(k){return"undefined"!==typeof FS&&k instanceof FS.ha||w(k),-k.ia}},L:function(a,b){S=b;try{var d=H(T()),e=H(T());FS.rename(d,e);return 0}catch(g){return"undefined"!==typeof FS&&g instanceof FS.ha||w(g),-g.ia}},t:function(a,b){S=b;try{var d=H(T()),e=T(),g=T();return FS.open(d,e,g).fd}catch(k){return"undefined"!==typeof FS&&k instanceof FS.ha||w(k),-k.ia}},p:function(a,b){S=b;return 0},o:function(a,b){S=b;try{var d=U.ma();FS.close(d);
return 0}catch(e){return"undefined"!==typeof FS&&e instanceof FS.ha||w(e),-e.ia}},n:function(){},d:function(){c.abort()},s:V,J:function(a,b){if(0===a)a=Date.now();else if(1===a&&(t||"undefined"!==typeof dateNow||(n||p)&&self.performance&&self.performance.now))a=W();else return Qa(22),-1;A[b>>2]=a/1E3|0;A[b+4>>2]=a%1E3*1E6|0;return 0},I:function(a,b,d){G.set(G.subarray(b,b+d),a);return a},h:function(a){if(!c.noExitRuntime&&(ka=!0,L=fb,M(Ga),c.onExit))c.onExit(a);c.quit(a,new v(a))},H:Ja,m:X,G:function(a){var b=
Date.now();A[a>>2]=b/1E3|0;A[a+4>>2]=b%1E3*1E3|0;return 0},r:function(a,b){a=new Date(1E3*A[a>>2]);A[b>>2]=a.getUTCSeconds();A[b+4>>2]=a.getUTCMinutes();A[b+8>>2]=a.getUTCHours();A[b+12>>2]=a.getUTCDate();A[b+16>>2]=a.getUTCMonth();A[b+20>>2]=a.getUTCFullYear()-1900;A[b+24>>2]=a.getUTCDay();A[b+36>>2]=0;A[b+32>>2]=0;A[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;A[b+40>>2]=Sa;return b},e:Ta,j:function(){return Ta.apply(null,arguments)},E:Ua,i:function(){return Ua.apply(null,
arguments)},g:Va,l:function(){return Va.apply(null,arguments)},D:La,C:function(a,b){Wa();a=new Date(1E3*A[a>>2]);A[b>>2]=a.getSeconds();A[b+4>>2]=a.getMinutes();A[b+8>>2]=a.getHours();A[b+12>>2]=a.getDate();A[b+16>>2]=a.getMonth();A[b+20>>2]=a.getFullYear()-1900;A[b+24>>2]=a.getDay();var d=new Date(a.getFullYear(),0,1);A[b+28>>2]=(a.getTime()-d.getTime())/864E5|0;A[b+36>>2]=-(60*a.getTimezoneOffset());var e=(new Date(2E3,6,1)).getTimezoneOffset();d=d.getTimezoneOffset();a=(e!=d&&a.getTimezoneOffset()==
Math.min(d,e))|0;A[b+32>>2]=a;a=A[Z()+(a?4:0)>>2];A[b+40>>2]=a;return b},B:function(a){Wa();var b=new Date(A[a+20>>2]+1900,A[a+16>>2],A[a+12>>2],A[a+8>>2],A[a+4>>2],A[a>>2],0),d=A[a+32>>2],e=b.getTimezoneOffset(),g=new Date(b.getFullYear(),0,1),k=(new Date(2E3,6,1)).getTimezoneOffset(),h=g.getTimezoneOffset(),l=Math.min(h,k);0>d?A[a+32>>2]=Number(k!=h&&l==e):0<d!=(l==e)&&(k=Math.max(h,k),b.setTime(b.getTime()+6E4*((0<d?l:k)-e)));A[a+24>>2]=b.getDay();A[a+28>>2]=(b.getTime()-g.getTime())/864E5|0;return b.getTime()/
1E3|0},z:function(a,b){var d=A[a>>2];a=A[a+4>>2];0!==b&&(A[b>>2]=0,A[b+4>>2]=0);b=(1E6*d+a/1E3)/1E3;if((n||p)&&self.performance&&self.performance.now)for(d=self.performance.now();self.performance.now()-d<b;);else for(d=Date.now();Date.now()-d<b;);return 0},y:function(a,b,d,e){function g(a,b,d){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=d[0]+a;return a}function k(a,b){return g(a,b,"0")}function h(a,b){function d(a){return 0>a?-1:0<a?1:0}var e;0===(e=d(a.getFullYear()-b.getFullYear()))&&
0===(e=d(a.getMonth()-b.getMonth()))&&(e=d(a.getDate()-b.getDate()));return e}function l(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function B(a){a=eb(new Date(a.ga+1900,0,1),a.oa);var b=l(new Date(a.getFullYear()+1,0,4));return 0>=
h(l(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var r=A[e+40>>2];e={ya:A[e>>2],xa:A[e+4>>2],na:A[e+8>>2],ka:A[e+12>>2],ja:A[e+16>>2],ga:A[e+20>>2],qa:A[e+24>>2],oa:A[e+28>>2],Ca:A[e+32>>2],wa:A[e+36>>2],za:r?H(r):""};d=H(d);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var q in r)d=d.replace(new RegExp(q,"g"),r[q]);var I="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
Ka="January February March April May June July August September October November December".split(" ");r={"%a":function(a){return I[a.qa].substring(0,3)},"%A":function(a){return I[a.qa]},"%b":function(a){return Ka[a.ja].substring(0,3)},"%B":function(a){return Ka[a.ja]},"%C":function(a){return k((a.ga+1900)/100|0,2)},"%d":function(a){return k(a.ka,2)},"%e":function(a){return g(a.ka,2," ")},"%g":function(a){return B(a).toString().substring(2)},"%G":function(a){return B(a)},"%H":function(a){return k(a.na,
2)},"%I":function(a){a=a.na;0==a?a=12:12<a&&(a-=12);return k(a,2)},"%j":function(a){return k(a.ka+bb($a(a.ga+1900)?cb:db,a.ja-1),3)},"%m":function(a){return k(a.ja+1,2)},"%M":function(a){return k(a.xa,2)},"%n":function(){return"\n"},"%p":function(a){return 0<=a.na&&12>a.na?"AM":"PM"},"%S":function(a){return k(a.ya,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.ga+1900,a.ja+1,a.ka,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.ga+1900,0,1),d=0===b.getDay()?b:eb(b,7-b.getDay());
a=new Date(a.ga+1900,a.ja,a.ka);return 0>h(d,a)?k(Math.ceil((31-d.getDate()+(bb($a(a.getFullYear())?cb:db,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(d,b)?"01":"00"},"%V":function(a){var b=l(new Date(a.ga+1900,0,4)),d=l(new Date(a.ga+1901,0,4)),e=eb(new Date(a.ga+1900,0,1),a.oa);return 0>h(e,b)?"53":0>=h(d,e)?"01":k(Math.ceil((b.getFullYear()<a.ga+1900?a.oa+32-b.getDate():a.oa+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.ga+1900,a.ja+1,a.ka,0,0,0,0)).getDay()},"%W":function(a){var b=
new Date(a.ga,0,1),d=1===b.getDay()?b:eb(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.ga+1900,a.ja,a.ka);return 0>h(d,a)?k(Math.ceil((31-d.getDate()+(bb($a(a.getFullYear())?cb:db,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(d,b)?"01":"00"},"%y":function(a){return(a.ga+1900).toString().substring(2)},"%Y":function(a){return a.ga+1900},"%z":function(a){a=a.wa;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.za},"%%":function(){return"%"}};
for(q in r)0<=d.indexOf(q)&&(d=d.replace(new RegExp(q,"g"),r[q](e)));q=Y(d,!1);if(q.length>b)return 0;F.set(q,a);return q.length-1},a:C,b:L};var gb=c.asm(c.ra,c.sa,buffer);c.asm=gb;var Na=c.___emscripten_environ_constructor=function(){return c.asm.R.apply(null,arguments)},Za=c.__get_daylight=function(){return c.asm.S.apply(null,arguments)},Ya=c.__get_timezone=function(){return c.asm.T.apply(null,arguments)},Z=c.__get_tzname=function(){return c.asm.U.apply(null,arguments)};
c._add_audio_frame=function(){return c.asm.V.apply(null,arguments)};c._add_video_frame=function(){return c.asm.W.apply(null,arguments)};c._add_video_frame_yuv420=function(){return c.asm.X.apply(null,arguments)};c._close_stream=function(){return c.asm.Y.apply(null,arguments)};var Aa=c._emscripten_replace_memory=function(){return c.asm._emscripten_replace_memory.apply(null,arguments)},Ra=c._free=function(){return c.asm.Z.apply(null,arguments)};c._free_buffer=function(){return c.asm._.apply(null,arguments)};
var E=c._malloc=function(){return c.asm.$.apply(null,arguments)};c._open_audio=function(){return c.asm.aa.apply(null,arguments)};c._open_video=function(){return c.asm.ba.apply(null,arguments)};c._write_header=function(){return c.asm.ca.apply(null,arguments)};var ma=c.stackAlloc=function(){return c.asm.fa.apply(null,arguments)};c.dynCall_v=function(){return c.asm.da.apply(null,arguments)};c.dynCall_vi=function(){return c.asm.ea.apply(null,arguments)};c.asm=gb;
c.then=function(a){if(c.calledRun)a(c);else{var b=c.onRuntimeInitialized;c.onRuntimeInitialized=function(){b&&b();a(c)}}return c};function v(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}v.prototype=Error();v.prototype.constructor=v;var fb;P=function hb(){c.calledRun||ib();c.calledRun||(P=hb)};
function ib(){function a(){if(!c.calledRun&&(c.calledRun=!0,!ka)){N||(N=!0,M(Ea));M(Fa);if(c.onRuntimeInitialized)c.onRuntimeInitialized();if(c.postRun)for("function"==typeof c.postRun&&(c.postRun=[c.postRun]);c.postRun.length;){var a=c.postRun.shift();Ha.unshift(a)}M(Ha)}}if(!(0<O)){if(c.preRun)for("function"==typeof c.preRun&&(c.preRun=[c.preRun]);c.preRun.length;)Ia();M(Da);0<O||c.calledRun||(c.setStatus?(c.setStatus("Running..."),setTimeout(function(){setTimeout(function(){c.setStatus("")},1);
a()},1)):a())}}c.run=ib;function w(a){if(c.onAbort)c.onAbort(a);void 0!==a?(ea(a),x(a),a=JSON.stringify(a)):a="";ka=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}c.abort=w;if(c.preInit)for("function"==typeof c.preInit&&(c.preInit=[c.preInit]);0<c.preInit.length;)c.preInit.pop()();c.noExitRuntime=!0;ib();


  return WasmEncoder;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
    module.exports = WasmEncoder;
  else if (typeof define === 'function' && define['amd'])
    define([], function() { return WasmEncoder; });
  else if (typeof exports === 'object')
    exports["WasmEncoder"] = WasmEncoder;
  